### ISSUE TITLE
Can this library be used to generate static images?

### ISSUE THREAD

**Issue by mersadk** [verybadcat/CSharpMath#18]
Can this library be used to generate static images (jpg, png..)? 
If it is not possible now, can it be added in future versions?

**Comment by Happypig375** [comment]
Yes, through SkiaSharp.
1. Install CSharpMath.SkiaSharp on a SkiaSharp-supported project
2. Take a look at [this page](https://forums.xamarin.com/discussion/88253/creating-and-drawing-an-image-with-skiasharp). In the code, let CSharpMath.SkiaSharp.MathPainter draw on the SKCanvas by calling MathPainter.Draw(). Instead of drawing some other shapes onto the canvas, MathPainter will take care of the drawing.
3. Test the code.

I am typing on mobile right now so I can't paste code here. Please try the steps though.

**Comment by Happypig375** [comment]
Great! Considering that your problem being solved, I'm closing this issue now. This will be linked in the to-be-written documentation for future reference.

**Comment by Happypig375** [comment]
Oops
