### ISSUE TITLE
\square is weird

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#48]
**Describe the bug**
The \\square command produces a square correctly but it also sets characters before and after it to its position.

**To Reproduce**
Type
```
123\square456
```
in the Try tab of Forms.Example.
**Expected behavior**
(Need research to find out)

**Screenshots**
(Cannot send pictures on mobile)

**Environment (please complete the following information):**
 - Platform: [e.g. CSharpMath.SkiaSharp, CSharpMath.Forms]
 - Package Version or Commit: 0.3.0-alpha
 - Device: Redmi 6

**Comment by FoggyFinder** [comment]
I think it can be because `square` command produces a placeholder.

Does it make sense to change it to something like that?

```cs
{ "square", Create(MathAtomType.Variable, Symbols.WhiteSquare) },
```

Then it won't look odd:

![square](https://user-images.githubusercontent.com/16510738/67581658-11874480-f751-11e9-9679-59496ada2198.jpg)

**Comment by Happypig375** [comment]
The root cause is that placeholders have weird positioning. We shouldn't just fix the symptoms.

**Comment by FoggyFinder** [comment]
I understand the problem with placeholder won't gone. I was just thinking what's better for "square" command itself.

**Comment by FoggyFinder** [comment]
Next shot :-)

Placeholder threats differently to any other _MathAtomType_ cases because of the [_AttributesMatch_](https://github.com/verybadcat/CSharpMath/blob/705a3f7f97284b7fd33b87b25615cb8d8617052a/CSharpMath/Display/Text/AttributedStrings/AttributedGlyphRun.cs#L36-L38):

So the input that contains `Placeholder` is not fused into a single run. Is it expected?

I had commented the check and did quick tests - I didn't notice anything wrong. There were no additional failed unit tests as well.

As I can see problem or with additional run or with that wrong range/positioning for an additional run during creation of _TextLineDisplay_ here:

```cs
public TextLineDisplay(
      AttributedString<TFont, TGlyph> text,
      Range range,
      TypesettingContext<TFont, TGlyph> context,
      List<IMathAtom> atoms) : this(
        text.Runs.Select(
          run => new TextRunDisplay<TFont, TGlyph>(run, new Range(range.Location, run.Length), context)
        ).ToList(), atoms)
```
it always goes from the start.

I assume replacement could be something like this:

```cs
public TextLineDisplay(
  AttributedString<TFont, TGlyph> text,
  Range range,
  TypesettingContext<TFont, TGlyph> context,
  List<IMathAtom> atoms) {
  var runs = new List<TextRunDisplay<TFont, TGlyph>>();
  int acc = 0 ;
  int i = 0;
  foreach (var run in text.Runs) {
    var textRun = new TextRunDisplay<TFont, TGlyph>(
      run, new Range(range.Location + acc, run.Length), context);
    runs.Add(textRun);
    acc += run.Length;
    if (i > 0) {
      var prev = runs[i - 1];
      textRun.Position =
        prev.Position.Plus(
            new PointF(
              prev.DisplayBounds.Width, prev.Position.Y
              )
            );
    }
    i++;
  }
  Runs = runs;
  Atoms = new IMathAtom[atoms.Count];
  atoms.CopyTo(Atoms);
}
```

The result will be:

![pic](https://user-images.githubusercontent.com/16510738/67850174-e87ffe80-fb18-11e9-864d-14bdf27349bf.jpg)

It's a quick dirty implementation just to show concept. I'm not sure is it correct way or not but the idea is here.

**Comment by FoggyFinder** [comment]
So, as far as I understand, the two main Qs are:

1. Placeholder is put in a separate `Run`. Is it correct/expected behaviour or not?
2. `Range`/`Position` for each `Run` are started from `0`/`(0,0)`. Is it correct/expected behaviour or not?

**Comment by Happypig375** [comment]
These are ported from iosMath so I'm not sure either.

**Comment by FoggyFinder** [comment]
uh-oh.
Any chance that you remember why there was adding a check `run1.Placeholder == run2.Placeholder` to the `AttributesMatch` [here](https://github.com/verybadcat/CSharpMath/commit/5816964453d2738f1b55a08afe06d0857bfabdf0) 

Initially it was just a:

`!(run1 is null || run2 is null) && EqualityComparer<TFont>.Default.Equals(run1.Font, run2.Font);`

and with it there is no the bug.

I tried to find related code in iosMath but I wasn't able to do it. I totally can't understand `Objective-C`. 

---

Is there are any samples with input that places in more than one Run? (except placeholder)

**Comment by Happypig375** [comment]
Hmmmm… That might have been an accidental change that wasn't removed. If removing it causes less bugs, then feel free to do so.
