### ISSUE TITLE
Incorrect index detection in the end of a list

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#64]
### To Reproduce

1. Type input: 1^{123} + 
2. Click after +

Index = [3]

![wrongIndex](https://user-images.githubusercontent.com/16510738/67496722-8a20cf00-f685-11e9-94ab-6668242e32ce.jpg)

### Expected behavior
Index  = [2]

**Comment by charlesroddie** [comment]
Also: cannot get cursor into this position by clicking:
![image](https://user-images.githubusercontent.com/19760720/67497272-aae12880-f675-11e9-805c-64b607e36bad.png)

Strangely this seems to be a minimal example. The presence of the second 1^1 is necessary, and the problem is increasing in the length of the first exponent (11).
