### ISSUE TITLE
Mess with unit testing frameworks 

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#95]
Currently there are 3 test projects:

| Project | Language | Unit testing framework |
|---- |--- |------|
| CSharpMath Tests            | C#            |  xunit  |
| CSharpMath.Editor Tests  | C#           |   xunit |
| TestsInFSharp                   | F#            | nunit |

2 languages and 2 frameworks. It looks a bit odd to me cause there is no additional separate F# API and therefore usage is pretty much the same.

Proposals:

1. Choose `xunit`, `nunit` or whatever and stick to it.
2. Rewrite tests to F# entirely. There are OS projects that uses F# for tests (For example, [WpfMath.Tests](https://github.com/ForNeVeR/wpf-math/tree/master/src/WpfMath.Tests). So I don't think it will be a problem for new contributors.

I know there is (was?) plan to use F# for ["core" library](https://github.com/charlesroddie/MathAtom) but since it won't happen in the near future maybe it make sense to rewrite only tests for now.

**Comment by Happypig375** [comment]
1. Will frameworks specifically for F#, e.g. [FsUnit](https://github.com/fsprojects/FsUnit), be desirable on top of whatever testing framework we use?
2. Are C# projects with F# tests a minority thus may be a problem for new contributors?

The rewrite might coincide with #58.

**Comment by charlesroddie** [comment]
Since most are in xunit currently we should take the nunit one to xunit.

I do not recommend FsUnit as it has some really bad syntax like `"ships" |> should not' (endWith "ss")`, with the unimportant advantage of semi-readability for non-programmers at the cost of extremely complex and inscrutable types.

There are some interesting F# testing libraries: randomized testing (giraffe, expecto), and quotation-based (unquote), but there is no need to use these unless they are considered helpful for particular tests.

I don't think having an extra project is a big cost. I doubt migrating existing tests to F# is worth it unless some of them need to be rewritten for other reasons.

**Comment by FoggyFinder** [comment]
> Are C# projects with F# tests a minority thus may be a problem for new contributors?

If it will be something well known for them like nunit or xunit then I don't think there will be any difficulties.

> I don't think having an extra project is a big cost. I doubt migrating existing tests to F# is worth it unless some of them need to be rewritten for other reasons.

It is just unclear where to add new tests. Both `CSharpMath.Editor Tests` and `TestsInFSharp` projects contains tests for Editor. Which of them has more priority?

**Comment by Happypig375** [comment]
>If it will be something well known for them like nunit or xunit then I don't think there will be any difficulties.

Until they see active patterns in conjunction with piping inside of a recursive function.
>It is just unclear where to add new tests. Both CSharpMath.Editor Tests and TestsInFSharp projects contains tests for Editor. Which of them has more priority?

Maybe it will be up to the code author's choice.

**Comment by Happypig375** [comment]
Should this be considered completed?

**Comment by FoggyFinder** [comment]
Yeah, closed
